-- Include after v36 and v37 inside one disposable BEGIN/ROLLBACK transaction.
-- Installers have BEGIN/COMMIT wrappers: strip them in the harness, never commit
-- this synthetic fixture. HMAC/context are real; Ed25519 bytes are synthetic
-- because the privileged service verifies the coordinator signature separately.
do $fair_dice_v37_smoke$
declare
  fixture_code text := 'V37A-' || translate(upper(substr(encode(extensions.gen_random_bytes(3), 'hex'), 1, 4)), '01', '23');
  guest_proof text := 'gproof:' || encode(extensions.digest(convert_to(gen_random_uuid()::text, 'UTF8'), 'sha256'), 'hex');
  guest_id text; initial jsonb; receipt jsonb; room_result jsonb; result jsonb; proof jsonb; derived jsonb;
  opening_state jsonb; roll_state jsonb; terminal_state jsonb;
  request_id uuid; first_epoch uuid; a integer; b integer;
  ledger private.fair_dice_requests%rowtype; vector private.fair_dice_requests%rowtype; golden jsonb;
begin
  if has_table_privilege('anon', 'private.fair_dice_requests', 'SELECT')
     or has_table_privilege('service_role', 'private.fair_dice_requests', 'UPDATE')
     or has_function_privilege('anon', 'public.accept_system_fair_dice_client_seed(uuid,text,text,uuid,text)', 'EXECUTE')
     or has_function_privilege('authenticated', 'public.configure_fair_dice_protocol(text)', 'EXECUTE')
     or not has_function_privilege('service_role', 'public.accept_system_fair_dice_client_seed(uuid,text,text,uuid,text)', 'EXECUTE') then
    raise exception 'v37 private entropy or service capability ACL is invalid.';
  end if;
  -- Golden vectors are independently generated by the Node prototype and shared
  -- browser protocol. They catch PostgreSQL JSON whitespace/nested escaping drift.
  vector.id := '22222222-2222-4222-8222-222222222222';
  vector.game_id := '11111111-1111-4111-8111-111111111111';
  vector.room_code := 'V37A-ABCD'; vector.nonce := 1; vector.variant := 'long';
  vector.label := 'opening'; vector.color := 'none'; vector.position_hash := repeat('a',64);
  vector.created_at := '2026-09-18T00:00:00.123Z'; vector.protocol := 'system-csprng-v1';
  vector.private_seed := repeat('1',64); vector.client_seed := repeat('2',64);
  vector.commitment := private.system_fair_dice_commitment(vector);
  if vector.commitment <> '03a06d40fd7d8adb5f0521626416a58980e9e69b9ccd6c02b4c76236d59714d5'
     or private.system_fair_dice_request_hash(vector) <> '9e55b0147bf52636f558872ed46e08412978e824c824d7653ccc94b88fe2963d' then
    raise exception 'v37 commitment or request JSON golden vector mismatch.';
  end if;
  derived := private.system_fair_dice_derived(vector);
  if derived->'dice' <> '[3,1]'::jsonb or derived->'counter' <> '0'::jsonb
     or derived#>>'{blocks,0}' <> 'da304697f862945d949a5246ee819ba513ef875e2b3a98b1e0561debdd4d4d77'
     or derived->>'sha256' <> '912d857980db5c061ca3f6198cb42a1aeea07559267bcb8809deb5a95c9922cd' then
    raise exception 'v37 HMAC/result golden vector mismatch.';
  end if;
  for golden in select value from jsonb_array_elements('[
    {"seed":"0000000000000000000000000000000000000000000000000000000000000010","label":"roll","color":"white","dice":[6,1],"counter":0,"sha256":"90b3da692b01f95a4212f7a0d50cbc88612cb3e1d2f2af71883ac90e3c917349"},
    {"seed":"0000000000000000000000000000000000000000000000000000000000000015","label":"opening","color":"none","dice":[5,3],"counter":2,"sha256":"0a1dab3eca6f467c757cc45b72bbef225813a4d1a82227082401ad2339a6f9fd"},
    {"seed":"0000000000000000000000000000000000000000000000000000000000000017","label":"roll","color":"white","dice":[4,4],"counter":0,"sha256":"67f15b56e23501889afa142ecc302b81687454de08baf79effdcaf93f5b5b73b"}
  ]'::jsonb) loop
    vector.private_seed := golden->>'seed'; vector.label := golden->>'label'; vector.color := golden->>'color';
    vector.commitment := private.system_fair_dice_commitment(vector);
    derived := private.system_fair_dice_derived(vector);
    if derived->'dice' <> golden->'dice' or derived->'counter' <> golden->'counter'
       or derived->>'sha256' <> golden->>'sha256' then
      raise exception 'v37 rejection sampling, earliest opening counter or ordinary-double vector mismatch.';
    end if;
  end loop;
  perform set_config('request.jwt.claims', '{"role":"service_role"}', true);
  perform set_config('request.jwt.claim.role', 'service_role', true);
  perform public.configure_fair_dice_policy(true);
  perform public.configure_fair_dice_protocol('system-csprng-v1');
  if public.get_fair_dice_policy() <> '{"enabled":true,"protocol":"system-csprng-v1"}'::jsonb then
    raise exception 'v37 activation policy is not visible.';
  end if;
  guest_id := private.guest_identity_from_proof(guest_proof);
  perform set_config('request.jwt.claims', '{"role":"anon"}', true);
  perform set_config('request.jwt.claim.role', 'anon', true);
  perform set_config('request.headers', jsonb_build_object('x-guest-id', guest_id, 'x-guest-proof', guest_proof,
    'x-client-info', 'supabase-js-web/smoke nardu-fair-dice-v36')::text, true);
  initial := jsonb_build_object(
    'variant', 'long', 'roomCode', fixture_code, 'mode', 'bot', 'startedAt', 1789680000000::bigint,
    'points', '{"24":{"color":"white","count":15},"12":{"color":"dark","count":15}}'::jsonb,
    'off', '{"white":0,"dark":0}'::jsonb, 'bar', '{"white":0,"dark":0}'::jsonb,
    'score', '{"white":0,"dark":0}'::jsonb, 'firstMoveDone', '{"white":false,"dark":false}'::jsonb,
    'headPlayedThisTurn', '{"white":false,"dark":false}'::jsonb,
    'turnMoves', '[]'::jsonb, 'dice', '[]'::jsonb, 'rolled', '[]'::jsonb, 'history', '[]'::jsonb,
    'turn', null, 'winner', null, 'openingRoll', null, 'finishedAt', null, 'resultType', null,
    'phase', 'opening', 'matchScore', '{"white":0,"dark":0,"target":5,"recordedWinner":null}'::jsonb
  );
  begin
    insert into public.rooms(code,variant,status,host_name,host_guest_id,host_registered,game_state)
    values(fixture_code,'long','joined','Fair v37 stale smoke',guest_id,false,initial);
    raise exception 'A v36-only client created a system room.';
  exception when invalid_parameter_value then null; end;
  perform set_config('request.headers', jsonb_build_object('x-guest-id', guest_id, 'x-guest-proof', guest_proof,
    'x-client-info', 'supabase-js-web/smoke nardu-fair-dice-v36 nardu-fair-dice-v37')::text, true);
  insert into public.rooms(code,variant,status,host_name,host_guest_id,host_registered,game_state,fair_dice_required,fair_dice_protocol)
  values(fixture_code,'long','joined','Fair v37 smoke',guest_id,false,initial,false,'drand-quicknet-v1');
  room_result := public.get_fair_dice_room(fixture_code); first_epoch := (room_result->>'gameId')::uuid;
  if room_result->'fairDiceRequired' <> 'true'::jsonb or room_result->>'fairDiceProtocol' <> 'system-csprng-v1' then
    raise exception 'System policy was not stamped from server settings.';
  end if;
  begin
    update public.rooms set fair_dice_protocol = 'drand-quicknet-v1' where code = fixture_code;
    raise exception 'An existing room changed its protocol.';
  exception when insufficient_privilege then null; end;
  receipt := public.reserve_fair_dice(fixture_code,'opening','none',repeat('0',64));
  if receipt <> public.reserve_fair_dice(fixture_code,'opening','none',repeat('f',64))
     or receipt ? 'round' or receipt ? 'privateSeed' or not receipt ? 'commitment'
     or (select count(*) from jsonb_object_keys(receipt)) <> 10 then
    raise exception 'System receipt is not an immutable public ten-field commitment.';
  end if;
  request_id := (receipt->>'id')::uuid;
  select * into ledger from private.fair_dice_requests where id = request_id;
  if ledger.round is not null or ledger.private_seed !~ '^[0-9a-f]{64}$'
     or ledger.commitment <> private.system_fair_dice_commitment(ledger)
     or ledger.client_seed is not null or ledger.client_seed_at is not null then
    raise exception 'System entropy was not created exactly once before the client challenge.';
  end if;
  result := public.get_fair_dice_request(request_id);
  room_result := public.get_fair_dice_room(fixture_code);
  if result ? 'privateSeed' or result#>'{request,privateSeed}' is not null
     or room_result#>'{pending,privateSeed}' is not null
     or room_result#>'{pending,request,privateSeed}' is not null then
    raise exception 'Unrevealed server entropy escaped into public receipts.';
  end if;
  begin
    perform public.accept_system_fair_dice_client_seed(request_id,repeat('2',64),fixture_code,first_epoch,receipt->>'positionHash');
    raise exception 'An anonymous player called the privileged acceptance RPC.';
  exception when insufficient_privilege then null; end;
  perform set_config('request.jwt.claims', '{"role":"service_role"}', true);
  perform set_config('request.jwt.claim.role', 'service_role', true);
  begin
    perform public.commit_fair_dice_proof(request_id,'{}'::jsonb);
    raise exception 'A seed was revealed before accepting a client challenge.';
  exception when check_violation then null; end;
  begin
    perform public.accept_system_fair_dice_client_seed(request_id,repeat('2',64),fixture_code,gen_random_uuid(),receipt->>'positionHash');
    raise exception 'A wrong game epoch accepted the client challenge.';
  exception when check_violation then null; end;
  begin
    perform public.accept_system_fair_dice_client_seed(request_id,repeat('2',64),fixture_code,first_epoch,repeat('f',64));
    raise exception 'A wrong board position accepted the client challenge.';
  exception when check_violation then null; end;
  begin
    perform public.accept_system_fair_dice_client_seed(request_id,'bad-seed',fixture_code,first_epoch,receipt->>'positionHash');
    raise exception 'A malformed client challenge was accepted.';
  exception when invalid_parameter_value then null; end;
  result := public.accept_system_fair_dice_client_seed(request_id,repeat('2',64),fixture_code,first_epoch,receipt->>'positionHash');
  if result->>'privateSeed' <> ledger.private_seed or result->>'clientSeed' <> repeat('2',64)
     or public.accept_system_fair_dice_client_seed(request_id,repeat('2',64),fixture_code,first_epoch,receipt->>'positionHash') <> result then
    raise exception 'The first client challenge is not durable/idempotent.';
  end if;
  begin
    perform public.accept_system_fair_dice_client_seed(request_id,repeat('3',64),fixture_code,first_epoch,receipt->>'positionHash');
    raise exception 'The accepted challenge was replaced to choose another result.';
  exception when unique_violation then null; end;
  select * into ledger from private.fair_dice_requests where id = request_id;
  if ledger.client_seed_at is null or ledger.client_seed_at < ledger.created_at then
    raise exception 'Challenge acceptance was not timestamped after the commitment.';
  end if;
  derived := private.system_fair_dice_derived(ledger);
  proof := jsonb_build_object('protocol','system-csprng-v1','request',receipt,
    'requestHash',private.system_fair_dice_request_hash(ledger),'receiptSignature',repeat('b',128),
    'commitReveal',jsonb_build_object('serverSeed',ledger.private_seed,'clientSeed',ledger.client_seed,
      'counter',derived->'counter','blocks',derived->'blocks'),
    'dice',derived->'dice','sha256Input',derived->>'sha256Input','sha256',derived->>'sha256','rerolls',derived->'counter');
  begin
    perform public.commit_fair_dice_proof(request_id,jsonb_set(proof,'{commitReveal,serverSeed}',to_jsonb(repeat('4',64))));
    raise exception 'A different server seed completed the proof.';
  exception when check_violation then null; end;
  begin
    perform public.commit_fair_dice_proof(request_id,jsonb_set(proof,'{commitReveal,clientSeed}',to_jsonb(repeat('3',64))));
    raise exception 'A different client seed completed the proof.';
  exception when check_violation then null; end;
  begin
    perform public.commit_fair_dice_proof(request_id,jsonb_set(proof,'{commitReveal,counter}','1024'::jsonb));
    raise exception 'An arbitrary opening counter completed the proof.';
  exception when check_violation then null; end;
  begin
    perform public.commit_fair_dice_proof(request_id,jsonb_set(proof,'{dice}','[6,6]'::jsonb));
    raise exception 'Injected physical dice completed the proof.';
  exception when check_violation then null; end;
  begin
    perform public.commit_fair_dice_proof(request_id,proof || jsonb_build_object('unexpected',true));
    raise exception 'Surplus system proof fields were accepted.';
  exception when check_violation then null; end;
  begin
    perform public.commit_fair_dice_proof(request_id,proof || jsonb_build_object('sha256Input','changed-input'));
    raise exception 'A changed displayed SHA-256 input completed the proof.';
  exception when check_violation then null; end;
  if public.commit_fair_dice_proof(request_id,proof) <> proof or public.commit_fair_dice_proof(request_id,proof) <> proof then
    raise exception 'System proof completion was not idempotent.';
  end if;
  begin
    perform public.commit_fair_dice_proof(request_id,proof || jsonb_build_object('receiptSignature',repeat('f',128)));
    raise exception 'A completed system proof changed.';
  exception when unique_violation then null; end;
  a := (proof#>>'{dice,0}')::integer; b := (proof#>>'{dice,1}')::integer;
  opening_state := initial || jsonb_build_object('phase','opening-result','turn',case when a>b then 'white' else 'dark' end,
    'rolled',proof->'dice','openingRoll',jsonb_build_object('host',jsonb_build_object('die',a),'guest',jsonb_build_object('die',b),
      'winnerColor',case when a>b then 'white' else 'dark' end,'fairDiceProof',proof),
    'history',jsonb_build_array(jsonb_build_object('opening',true,'host',a,'guest',b,
      'sha256',proof->>'sha256','sha256Input',proof->>'sha256Input','fairDiceProof',proof)));
  perform public.commit_fair_dice_state(fixture_code,opening_state,0,request_id);
  begin
    perform public.accept_system_fair_dice_client_seed(request_id,repeat('2',64),fixture_code,first_epoch,receipt->>'positionHash');
    raise exception 'A consumed reservation accepted another challenge.';
  exception when check_violation then null; end;
  roll_state := opening_state || jsonb_build_object('phase','roll','rolled','[]'::jsonb);
  perform public.commit_fair_dice_state(fixture_code,roll_state,1,null);
  perform set_config('request.jwt.claims', '{"role":"anon"}', true);
  perform set_config('request.jwt.claim.role', 'anon', true);
  result := public.get_fair_dice_request(request_id);
  if result ? 'privateSeed' or result->'proof' <> proof then raise exception 'Public historical proof access is broken.'; end if;
  receipt := public.reserve_fair_dice(fixture_code,'roll',roll_state->>'turn',null);
  request_id := (receipt->>'id')::uuid;
  if (receipt->>'nonce')::integer <> 2 then raise exception 'System nonce did not advance.'; end if;
  terminal_state := roll_state || jsonb_build_object('phase','over','winner','dark','dice','[]'::jsonb,'rolled','[]'::jsonb,
    'history',jsonb_build_array(jsonb_build_object('resign',true,'color','white','winnerColor','dark')) || (roll_state->'history'));
  perform set_config('request.jwt.claims', '{"role":"service_role"}', true);
  perform set_config('request.jwt.claim.role', 'service_role', true);
  perform public.commit_fair_dice_state(fixture_code,terminal_state,2,null);
  begin
    perform public.accept_system_fair_dice_client_seed(request_id,repeat('2',64),fixture_code,first_epoch,receipt->>'positionHash');
    raise exception 'A cancelled terminal reservation accepted new entropy.';
  exception when check_violation then null; end;
  result := public.reset_fair_dice_game(fixture_code,initial,3);
  if (result->>'gameId')::uuid = first_epoch or (select fair_dice_protocol from public.rooms where code=fixture_code) <> 'system-csprng-v1'
     or (select count(*) from private.fair_dice_requests where room_code=fixture_code) <> 2 then
    raise exception 'Rematch lost immutable room policy, epoch uniqueness or old evidence.';
  end if;
  -- Changing the new-room default must not change this existing system room.
  perform public.configure_fair_dice_protocol('drand-quicknet-v1');
  perform set_config('request.jwt.claims', '{"role":"anon"}', true);
  perform set_config('request.jwt.claim.role', 'anon', true);
  receipt := public.reserve_fair_dice(fixture_code,'opening','none',null);
  if not receipt ? 'commitment' or receipt ? 'round' or (receipt->>'nonce')::integer <> 1
     or (receipt->>'gameId')::uuid = first_epoch then raise exception 'Existing system room was downgraded after policy rollback.'; end if;
  raise notice 'Fair v37 rollback smoke passed: golden vectors, policy isolation, private entropy, ordered seeds, idempotence, HMAC binding, proof history, terminal cancellation, rematch.';
end;
$fair_dice_v37_smoke$;
